### ISSUE TITLE
Flagged by VirusTotal

### ISSUE THREAD

**Issue by explodeo** [daleffe/rdp-port-knocking#2]
Source code flagged as Trojan:Script/Wacatac.B!ml
EXE in releases is flagged By crowdstrike and endgame (ML scores are >60%).
![image](https://user-images.githubusercontent.com/21688716/130722695-6cd19520-77f1-42c6-9bdd-29aa68172d97.png)
![image](https://user-images.githubusercontent.com/21688716/130722726-f0b13224-cd09-4e28-9cd8-4a876392ab75.png)

**Comment by firepacket** [comment]
@cmorcom
### This is stupidity. That's a very low score. Close this.

**Comment by explodeo** [comment]
Forgot to follow-up. 1-Week Sandbox testing verified the tool is benign
